### PR TITLE
fix: ignoring dangling images from image list 

### LINKED ISSUE #18: BUG 🐞: Crash on launch
**Describe the bug**

The application crashes upon launch:

```
panic: runtime error: slice bounds out of range [:1] with capacity 0────────────────────────────────────────────────────────────────────────────────────────────────────┘

                                                                    goroutine 13 [running]:
                                                                                           github.com/ajayd-san/gomanagedocker/tui.transformListNames({0xfe5320, 0x0, 0x0})
                                                                                                                                                                           	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/types.go:241 +0x2df
                                                                                                                                          github.com/ajayd-san/gomanagedocker/tui.imageItem.getName(...)
                           	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/types.go:76
                                                                                                                                                                   github.com/ajayd-san/gomanagedocker/tui.MainModel.fetchNewData.func1()
                                                            	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/mainModel.go:730 +0x11f
                                  created by github.com/ajayd-san/gomanagedocker/tui.MainModel.fetchNewData in goroutine 1
                                                                                                                          	/root/.gvm/pkgsets/go1.21.0/global/pkg/mod/github.com/ajayd-san/gomanagedocker@v1.1.2-0.20240717212957-c2b21f4eb981/tui/mainModel.go:724 +0x345
                                                                                                  #
```

The crash also left the terminal in a very borked state, I had a similar issue with my [gollama](https://github.com/sammcj/gollama) application and I think the fix was to add a `fmt.Print("\033[H\033[2J")` upon exit to reset the term 😅 

**To Reproduce**
Steps to reproduce the behaviour:

This I'm not sure about actually but my specs below.

```shell
go install github.com/ajayd-san/gomanagedocker@HEAD
gomanagedocker
```

**Expected behaviour**

No crash to occur

**Screenshots**
N/A

**Server (please complete the following information):**

 - OS: Fedora 40
 - gmd Version: 1.3
 - Docker: 27.0.3, build 7d4bcd8
 - nvidia-container-toolkit: 1.16.0

**Additional context**

### PR DESCRIPTION
**Pull request by ashishkhuraishy**
[FIX] App panics on startup

When one or more dangling images where found, the app crashed on startup because [here](https://github.com/ajayd-san/gomanagedocker/blob/7d0138e1c9d5f7b0eb919d24ec95d069b209f45b/tui/types.go#L241) trying to access out of bounds object from an empty array

Solved it by only considering non-dangling images as part of image list, such that there would be atleast one valid tag on the image

fixes #18

### CODE REVIEW

**Comment by ajayd-san** [comment]
Hey, Thanks for the PR. That should work.

However, can you do that check on `types.transformListNames` ? I would prefer this for 2 reasons: 

1. Easier to test (I've already added to test case and pushed to `dangling-images-hotfix` so you just pull my changes and test your change) 
2. We use `transformListNames` while making all `containers`, `images` and `volumes`. So this change would prevent such an error from occurring in the future for any type (even tho it's pretty rare). 


And push to `dangling-images-hotfix`, I'll merge to main by tonight.

Thanks!

**Comment by ajayd-san** [comment]
Hey, thanks for the PR. 

Also I'd like a test case if you can add one. 

Could you also add a check in `types.transformListNames` (check if input array is empty and return "" if it is). 

Push your changes to `dangling-images-hotfix` and I'll merge to main by tonight.

thanks!

**Comment by ashishkhuraishy** [comment]
@ajayd-san the changes for fix + some linting errors has been fixed

**Comment by ajayd-san** [comment]
Perfect. Thanks for your contribution!

**Pull request merged**
