### PR TITLE
fix: reorder the height and width in WindowTooSmallModel

### PR DESCRIPTION
**Pull request by pithecuse527**
### Description
Change the order of the height and width displayed in WindowTooSmallModel 

image

### Related Issue
#28 

### Changed Made
- Reorder the WindowTooSmallModel Width and Height to display properly
- Added test cases for the WindowTooSmallModel

### CODE REVIEW

**Comment by ajayd-san** [comment]
Hey, 

One small change, it would be helpful to add the minimum dimensions required as well. 

Can you add something like `Min Width: 65, Min Height: 25` between those two lines? 

Thanks

**Comment by pithecuse527** [comment]
Min. requirements added!

image

**Comment by ajayd-san** [comment]
I think it would be better to come up with something concise: 

`Minimum dimensions needed - Width: 65, Height: 25`

Please change to this instead.

**Comment by pithecuse527** [comment]
Done!

image

**Comment by ajayd-san** [comment]
Perfect!!

Thanks for your help @pithecuse527

**Comment by pithecuse527** [comment]
BTW,
It is advisable to use constant variables for minimum values, such as the minimum height for window size or the threshold for toggling the info box. If needed, we can address this in another issue.

**Comment by ajayd-san** [comment]
Yes, I totally agree. 

If you can address that, that would be great. 

- [ ] specify min heights and widths need for tui
- [ ] specify min heights and widths needed for infobox 



I already have ratios in constants in mainModel.go, so that is not needed: 
```go
// dimension ratios for infobox
const infoBoxWidthRatio = 0.55
const infoBoxHeightRatio = 0.6
```

Create a new issue and we can discuss more over there if required. Thanks!

**Pull request merged**
